### ISSUE TITLE
Proposal - Gravity Models of Migration

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/ph-submissions#171]
The Programming Historian has received the following proposal for a lesson on 'Gravity Models of Migration' by Adam Crymble (@acrymble). The proposed learning outcomes of the lesson are:
     
•	An overview of gravity models of migration and what they can and cannot be used for.
•	Conducted a gravity modelling of migration using real historical data.
•	Written computer code that can be repurposed on your own historical data.

This tutorial is planned as a spin-off outcome of the Programming Historian workshop at Bogota, 1-3 August 2018.
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 3rd August 2018. The author agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 03/08/2018, the editor will attempt to contact the author. If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author.
 
The main editorial contact for this lesson is @amsichani. If there are any concerns from the authors they can contact the Ombudsperson @ianmilligan1 or @amandavisconti.

**Comment by acrymble** [comment]
I am behind on this because running the workshop in Bogota meant a lot of work rather than writing!

Sorry. I will try to get this to you by 20 August. If I miss that deadline I think it's fair for you to close this until I follow through. (I will do my best).

**Comment by amsichani** [comment]
thanks for the update @acrymble ! Lets keep 20th August as a new deadline but as I will be on holidays, you could have a silent extension until the 28th of August ;-)

**Comment by acrymble** [comment]
I've got a fairly advanced draft of this, but I need to do some more research, which will likely take some time. So I am going to close this while I keep working and I will contact you in future when I've finished. Sorry for the delay but I want to get it right.

**Comment by amsichani** [comment]
thanks for the update @acrymble .

**Comment by amsichani** [comment]
re-opening this , as @acrymble is currently working on it, need to resolve [this](https://github.com/programminghistorian/jekyll/issues/1027) first

**Comment by acrymble** [comment]
@amsichani I have a couple of formatting issues with the lesson that I need help resolving. They are on paragraphs 90, 127, and 128.

On 90 I have a big table of data that is too wide for the screen.

127 and 128 are formulas that are too wide.

Is there a fix for this problem?

**Comment by acrymble** [comment]
@mdlincoln I got a bunch of failure to build emails last night when tweaking this lesson. The preview is now not in sync with the most up to date copy of the file (http://programminghistorian.github.io/ph-submissions/lessons/gravity-model). Can you advise what I've done wrong?

**Comment by walshbr** [comment]
@acrymble - sorry to jump in here, but can you check now to see if the preview is in sync with what you're expecting? I think this is likely related to Antonio's issue that he emailed about over the weekend. If one person is getting errors elsewhere in the repo that prevent it from building subsequent commits by different people working on this same branch would also have those errors. Also, if you look at the commit history here - https://github.com/programminghistorian/ph-submissions/commits/gh-pages - you can see the series of red X's next to the commits you made last week. After I pushed up a couple fixes over the weekend we switched to a green √. The X means that even though you have the most up to date files in the repo the site itself didn't build correctly and would appear out of date. Tl;DR - this might have been fixed so let me know if that's not the case.

**Comment by acrymble** [comment]
@walshbr thanks for taking a look. It's still not showing properly (it's showing the pre-change version). I had a look at my changes and they're pretty basic, so I don't think I'm screwed anything up. Is there something I should check?

**Comment by acrymble** [comment]
@amsichani sorry for the extraordinary delay. This proved much more difficult to master than I expected!

I have finished my revisions on this draft. I will note that there are still some technical issues with its rendering:

- Table 3 does not fit horizontally on the page and is cut off. This is confusing for the reader. I suspect it is a CSS issue
- wide formulas that use the double-dollar-sign formatting codes are cut off horizontally. I suspect it is a CSS issue. See paras 125, 130, 131

Apart from these issues, I would like to submit this tutorial formally at this stage.

**Comment by acrymble** [comment]
@amsichani can you let me know if you've received this?

**Comment by amsichani** [comment]
@acrymble  received- sorry for the delay from my part. I m now going to open a formal submission/review ticket for this lesson and we could work in parallel through the layout issues.

**Comment by acrymble** [comment]
We can close this because there's now a submission ticket.
