### ISSUE TITLE
Review ticket for "Installing Omeka"

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/ph-submissions#6]
This ticket will provide a space for the peer review of http://programminghistorian.org/lessons/installing-omeka. Unlike our standard workflow now in use, this lesson resides in the jekyll repository (not here in ph-submission), but it will be useful to keep all review tickets in one place.

**Comment by fredgibbs** [comment]
The new, formal announcement:

_The Programming Historian_ has received the a new tutorial: **Installing Omeka** by @JonathanReeve. This lesson is now under review and can be read at:

http://programminghistorian.org/lessons/installing-omeka

I will act as editor for the review process. My role is to solicit two reviews and to manage the discussion, which will take the form of comments on this ticket. We aim to complete this process within 4 weeks. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback **also on this discussion thread**, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). 

_The Programming Historian_ embraces openness in its review process, and endeavors to keep the review conversation here on GitHub. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @miriamposner if you feel there's a need for an ombudsperson to step in.

**Anti-Harassment Policy**
_

> This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.
> 
> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspersons (Ian Milligan or Miriam Posner - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

_

**Comment by mhbeals** [comment]
Thank you, @JonathanReeve, for your very helpful lesson. For your reference, I have undertaken the entire lesson using an Amazon Web Service Ubuntu virtual server.

First, I believe your introduction is sufficiently welcoming and the reasons for why you want to install Omeka directly are definitely sound. I also think it was interesting for highlighting the existence of AWS's free 12-month trial, which was previously unknown to me. You might also want to explain how the skills learned here might be transferable to other directly installed web environments.

**Step one:** I cannot comment on the Shared Server, as I did not have one available as the moment, but can offer the following points regarding the AWS installation.
- First, I would place your comment regarding choosing an Ubuntu server in bold, or otherwise separate it out typographically.  I missed this comment the first time through and unthinkingly used a Linux server, with frustrating results.
- Second, I would suggest going into more detail about how to set up the AWS server. You did point to instructions via Amazon, but these were not as friendly or direct as your own tutorial and having to switch between tutorials could very easily put someone off the installation process if something goes awry. This may be a problem, I realise, if AWS changes after publication of this tutorial, but I would still argue that a bit more in-tutorial advice would be helpful especially in terms of using a standalone or java-based SSH. I chose the latter.

**Step Two**: This part of the tutorial was clear and easy to follow. There were only a few minor points:
- You don't explain what the flags are doing. This is a minor point but will help make the skills learned here transferable and feel less like monkey-see, monkey-do
- When creating a database and username, I received an error message when using `'mhbeals_omeka'` and had to remove the inverted commas, using just `mhbeals_omeka` instead
- After each command, a message was returned that rows were altered. It might be worth stating what these return messages should be, as a way of the reader checking that it worked.  That 0 rows were affected in some steps looks like nothing has happened (when it has).
- You don't explicitly state how to leave the mysql database, and I Esc'd, Cntl+C'd and Cntl+X'd for a bit until I wandered my way out.

**Step-Three**: This sections was also easy to follow, however:
- I could not execute any of the commands in this section as written without receiving permission errors. Instead, I had to prefix `sudo` to each command
- Unzip was not previously installed and I had to use `sudo apt-get install unzip` before getting started

**Step-Four**: This section was fine, but may have the following issues:
- For those not familiar with Ubuntu, it might be worth adding a line about changing directories.  As a DOS-child myself, I kept forgetting the initial `/` and that I could not move up/down without typing in the entire path
- I needed to use `sudo nano db.ini` rather than `nano db.in`
- The images are very clear and the text generally so, but for those using a screen reader, it might be worth putting each change in as a separate bullet point and acknowledging that you need to include the speech marks

Unfortunately, once I completed your tutorial, I went to my DNS address and received a general error message from Omeka.  I attempted to diagnose this via Omeka's troubleshooting guide and other sites, and it appeared to be a "mod_rewrite is not enabled" error.  I edited setting for .htaccess and apache2 with no success.  I also attempted to install an early version of Omeka (2.0 rather than 2.4) on a clean server but with the same result.  I am afraid, therefore, I was thus never able to activate my site. There were some forums indicating that Omeka 2.4 did not 'play nice' with the new version of Apache, but I cannot comment directly on this.

If you could help me identify what has gone awry, I would be happy to re-run the tutorial and offer you further comments.

At this stage, however, I think this is a helpful (and suitably brief) tutorial and I very much hope to get my Omeka site up and running soon.

-M. H. Beals

**Comment by fredgibbs** [comment]
Thanks @mhbeals! These are all great comments and suggestions. It's unfortunate that you could not end up with a successful installation, but I think it provides very helpful troubleshooting for the lesson.

@JonathanReeve, I'm still working on getting another review, but I don't see any comments in the review that should not be addressed--all seem pretty minor, most requiring a small edit or just a sentence or two of additional explanation or clarification. 

It's always hard to troubleshoot from afar, but any suggestions on how to address the mod_rewrite error or other problems that you've encountered in your experience helping others install Omeka would be super helpful.

One early suggestion to "You might also want to explain how the skills learned here might be transferable to other directly installed web environments," I think this is a very good idea--and one that would only require a few sentences or an overview of the skills put to practice here that are often used elsewhere as well. I highlight this only because it can seem like it's getting off-topic (and _could_ become an unwieldy task), but I think it helps keep this lesson in spirit with the others, which are meant to be more useful than the specific directions they supply. 

At this point, I think it would be useful to address these issues before another reviewer goes through the tutorial, just to avoid similar sticking points, especially since it could not be completed successfully. Please let me know what your expected timeline is for revisions. Thanks!

**Comment by JonathanReeve** [comment]
Hi @mhbeals and @fredgibbs! Thanks for the very useful comments. It took me forever to get back to this (I had excruciatingly busy end-of-semester), but I just finished revisiting this article to address these issues and suggestions. I added the commits to [my original PR #231](https://github.com/programminghistorian/jekyll/pull/231), but if belongs elsewhere, let me know, and I'd be happy to move it. You can find a list of changes on [the commit history](https://github.com/JonathanReeve/programminghistorian/commits/installing-omeka-index) for my fork, but in summary, I added a sentence in the introduction about possible broader applications for this sort of technique, added root user and mod_rewrite instructions, and fixed a few more minor issues. I tested the instructions again on Digital Ocean, and everything seems to work, as far as I can tell. If you test it again, let me know if everything works as expected. I'll get back to you much more quickly this time around, now that the semester's over. Thanks again! I'm looking forward to seeing this article in the _Programming Historian_.

**Comment by fredgibbs** [comment]
Hi @JonathanReeve! Thanks for all the updates and improvements. No worries about the delay. As per our normal editorial procedure, we should have one other reader go through the instructions, even as you have thoroughly incorporated the excellent suggestions from @mhbeals. We can recruit someone to go through the lesson, but I thought I'd first ask if you know anyone who is thinking about installing Omeka anyway, and who might want to run through the tutorial and provide feedback. If so, they can post comments on this thread or send feedback to me and I'll post them. If not, that's fine; we'll find a volunteer. Thanks again!

**Comment by mhbeals** [comment]
@JonathanReeve and @fredgibbs 

Thanks for this.  I have gone through the tutorial again.  I am still having some problems I am afraid (so a third reviewer would certainly help to ensure its not just my setup on AWS).  I still need to use SUDO for ALL commands; the su root command doesn't seem to work for me and at the end I end up with a access for user error on the website.   Thanks again for this lesson, it looks really good!

**Comment by wcaleb** [comment]
The images for this lesson need to be fixed using the `figure` syntax described [here](http://programminghistorian.org/new-lesson-workflow#figures). Images for the lesson will also need to be placed in their own subdirectory.

**Comment by JonathanReeve** [comment]
Hi @fredgibbs et al. Thanks for the feedback. I've just added a few more commits to my original PR #231, fixing a few things. I tested it on AWS myself and discovered that AWS is much more complicated than I'd originally imagined (I've been a DigitalOcean user for a while now). Port forwarding isn't enabled by default, which means there's an added overhead to installing a web server. I've added a paragraph describing this process, but I try to dissuade novice users from using AWS in the intro, as well. That having been said, I've updated the instructions so that they all work on AWS now. @mhbeals, it turns out Amazon doesn't allow you to run `su root`, but will allow `sudo su root`, so I've added that. Also, @wcaleb, I've updated the figure syntax to the new style, and placed the images in a subdirectory with the lesson stub. Let me know if everything looks good. I'll send out a tweet and see if anyone out there is installing Omeka and wants to test drive the lesson, but also let me know if you find someone else to go through the tutorial, as well.

**Comment by wcaleb** [comment]
Image syntax looks right to me!

**Comment by fredgibbs** [comment]
Thanks @mhbeals for rechecking the lesson and @JonathanReeve for further revisions! I've looked at the lesson as well and it seems good to go at this point, so I've merged all requests and this lesson is now published. I will close this review thread, but we can always create new tickets if we learn of other potential issues; it seems like the basic workflow has been well covered, however. Thanks again!

**Comment by JonathanReeve** [comment]
Awesome! Glad to see it up. Let me know if any issues come up, and I'd be happy to revise the lesson.

**Comment by ElaineY2022** [comment]
Hi Jonathan, 
Thank you for the steps. 
I have some issue and stuck at the last step which I cannot let run the installation of the Omeka. 
Seems the code "chown -R www-data:www-data" is not working. 
Could you please give me some suggestion? Thank you.

**Comment by josircg** [comment]
Hi @ElaineY2022 You miss a "." (dot) at the end. The full command is:

`chown -R www-data:www-data .`

**Comment by ElaineY2022** [comment]
> Hi @ElaineY2022 You miss a "." (dot) at the end. The full command is:
> 
> `chown -R www-data:www-data .`

Hi , Thank you for pointing that out. Actually, I tried but it's not working. The installation is still not running.

**Comment by JonathanReeve** [comment]
Hi @ElaineY2022, this isn't really a troubleshooting forum, but when you say that that command doesn't work, do you mean that it throws an error? Or that the command succeeds, but doesn't succeed in changing the permissions of that folder? Maybe [the official documentation could help](https://omeka.org/classic/docs/Installation/Installation/)
